#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create our folders
mkdir -p \
    /icloud \
    /config/session_data

# # default config file
# cp -n \
#     /defaults/pyload.cfg \
#     /config/settings/pyload.cfg

# permissions
lsiown -R abc:abc \
    /app \
    /config
lsiown abc:abc \
    /icloud
